// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4WaV15QKzUFe50a5mCkfCuM3mmR2jSc',
    appId: '1:801745646461:web:12496beb48660b8ac9d214',
    messagingSenderId: '801745646461',
    projectId: 'example1-2a33b',
    authDomain: 'example1-2a33b.firebaseapp.com',
    storageBucket: 'example1-2a33b.appspot.com',
    measurementId: 'G-1G6X9EZR8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTO0YavUqx1DmOQZuC5pnNFlMaUlqrtlQ',
    appId: '1:801745646461:android:aebe08730ebff5c8c9d214',
    messagingSenderId: '801745646461',
    projectId: 'example1-2a33b',
    storageBucket: 'example1-2a33b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOs_qfOHzOjBklxQjI8XpHutv3BVBc_k8',
    appId: '1:801745646461:ios:255e7ecc3d8f78f9c9d214',
    messagingSenderId: '801745646461',
    projectId: 'example1-2a33b',
    storageBucket: 'example1-2a33b.appspot.com',
    iosBundleId: 'com.example.someapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOs_qfOHzOjBklxQjI8XpHutv3BVBc_k8',
    appId: '1:801745646461:ios:3ce378303b9fcda2c9d214',
    messagingSenderId: '801745646461',
    projectId: 'example1-2a33b',
    storageBucket: 'example1-2a33b.appspot.com',
    iosBundleId: 'com.example.someapp.RunnerTests',
  );
}
